name: Update news

on:
  workflow_dispatch: {}
  schedule:
    - cron: '17 */6 * * *'  # every 6 hours

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # allow pull --rebase

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Generate site
        run: python scripts/generate.py

      # Keep repo in sync but don't fail if nothing to commit
      - name: Commit changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "chore: refresh news [skip ci]" || echo "No changes to commit"

      # Rebase onto latest main to avoid non-fast-forward errors, then push
      - name: Rebase and push
        run: |
          git pull --rebase origin ${{ github.ref_name }}
          git push

      # Deploy via Pages (since Pages source is set to GitHub Actions)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4