name: Update news

on:
  workflow_dispatch: {}
  schedule:
    - cron: '17 */6 * * *'  # every 6 hours

permissions:
  contents: write        # to commit changes back to the repo
  pages: write           # to deploy to GitHub Pages
  id-token: write        # required by actions/deploy-pages

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Generate site
        run: python scripts/generate.py

      # Optional but recommended so your repo always has the latest JSON/HTML
      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "chore: refresh news [skip ci]" || echo "No changes to commit"
          git push

      # Upload the current repository content (including the freshly generated files)
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4