name: Update news

on:
  workflow_dispatch: {}
  schedule:
    - cron: '17 */6 * * *'     # every 6 hours
  push:
    paths:
      - 'feeds.yml'
      - 'scripts/**'
      - 'templates/**'
      - 'assets/**'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Generate site
        run: python scripts/generate.py

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # deploy the repository root (index.html, data/, assets/, etc.)

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4