name: Update news

on:
  workflow_dispatch: {}
  schedule:
    - cron: '17 */6 * * *'  # every 6 hours at minute 17

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Generate site
        run: |
          python scripts/generate.py

      - name: Commit and push changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "chore: refresh news [skip ci]" || echo "No changes to commit"
          git push
